package com.intita.forum.modelswrappers;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import org.hibernate.validator.constraints.NotBlank;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonView;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import com.intita.forum.jsonview.Views;
import com.intita.forum.models.ForumCategory;
import com.intita.forum.models.ForumCategoryStatistic;
import com.intita.forum.models.ForumTopic;
import com.intita.forum.models.IntitaUser;
import com.intita.forum.models.TopicMessage;
import com.intita.forum.models.IntitaUser.IntitaUserRoles;
@JsonIdentityInfo(generator=ObjectIdGenerators.PropertyGenerator.class, property="id")
public class ForumTopicJsonWrapper {
	private Long categoryId;
	private Long id;
	private boolean active;
	private Date date;
	private String name;
	private boolean pinned;
	private short type;
	private Boolean isAutoGenerated;
	private IntitaUserJsonWrapper author;
	private boolean isAccessible = true;
	private List<Long> topicMessagesIds = new ArrayList<Long>();
public ForumTopicJsonWrapper(ForumTopic topic){
	this.categoryId = topic.getCategory().getId();
	this.id = topic.getId();
	this.active = topic.isActive();
	this.date = topic.getDate();
	this.name = topic.getName();
	this.pinned = topic.isPinned();
	this.type = topic.getType();
	this.isAutoGenerated = topic.getIsAutoGenerated();
	this.author = new IntitaUserJsonWrapper(topic.getAuthor());
	for(TopicMessage message : topic.getTopicMessages())
		topicMessagesIds.add(message.getId());
}
public Long getCategoryId() {
	return categoryId;
}
public void setCategoryId(Long categoryId) {
	this.categoryId = categoryId;
}
public Long getId() {
	return id;
}
public void setId(Long id) {
	this.id = id;
}
public boolean isActive() {
	return active;
}
public void setActive(boolean active) {
	this.active = active;
}
public Date getDate() {
	return date;
}
public void setDate(Date date) {
	this.date = date;
}
public String getName() {
	return name;
}
public void setName(String name) {
	this.name = name;
}
public boolean isPinned() {
	return pinned;
}
public void setPinned(boolean pinned) {
	this.pinned = pinned;
}
public short getType() {
	return type;
}
public void setType(short type) {
	this.type = type;
}
public Boolean getIsAutoGenerated() {
	return isAutoGenerated;
}
public void setIsAutoGenerated(Boolean isAutoGenerated) {
	this.isAutoGenerated = isAutoGenerated;
}

public List<Long> getTopicMessagesIds() {
	return topicMessagesIds;
}
public void setTopicMessagesIds(List<Long> topicMessagesIds) {
	this.topicMessagesIds = topicMessagesIds;
}
public static List<ForumTopicJsonWrapper> convertList(List<ForumTopic> topics){
	List<ForumTopicJsonWrapper> result= new ArrayList<ForumTopicJsonWrapper>();
	for (ForumTopic topic : topics)
		result.add(new ForumTopicJsonWrapper(topic));
	return result;
}
public IntitaUserJsonWrapper getAuthor() {
	return author;
}
public void setAuthor(IntitaUserJsonWrapper author) {
	this.author = author;
}
}
